pipeline {
agent any
stages {
stage('Checkout') {
steps {
git url: 'https://github.com/rohith308/gittagging.git'
}
}
stage('Tagging') {
steps {
sh 'git tag -a tag1 -m "Version 1.0"'
sh 'git push --tags'
}
}
}
}
