pipeline {
agent any
stages {
stage('Checkout') {
steps {
git url: 'https://github.com/rohith308/cicd.git'
}
}
stage('Tagging') {
steps {
sh 'git tag -a v1.0 -m "Version 1.0"'
sh 'git push origin --tags'
}
}
}
}
